name: Daily CI

on:
  schedule:
    - cron: '23 14 * * 1-5'

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: fredshone/actions/.github/workflows/python-install-lint-test.yml@main
    with:
      os: ubuntu-latest
      py3version: "11"
      notebook_kernel: ntsx
      pytest_args: '--no-cov'  # ignore coverage
      cache_mamba_env: false
      lint: false
      mamba_env_name: daily-ci